{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pixlfox.scriptablemc",
    "module": "buildtools",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "buildtools-1.0.3.jar",
          "url": "buildtools-1.0.3.jar",
          "size": 57932,
          "sha512": "15698b86ffad46e8edd45b0b94c9e9a643dccaefcbfde4e38fcee6a03468deabf391d0d5eeef6d239d51477cd8f38a48c26b19fd1a8b11cc7632970364328dce",
          "sha256": "61f468f2496c7963755c8f1d903b485669f2c9feca1344ffa3641bdab9aee435",
          "sha1": "1d9ed63f2558ea31bed3e81e6b10008d03865a60",
          "md5": "c3e079f99c502a13c4e1d1106bff6405"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.15"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        }
      ],
      "files": [
        {
          "name": "buildtools-1.0.3.jar",
          "url": "buildtools-1.0.3.jar",
          "size": 57932,
          "sha512": "15698b86ffad46e8edd45b0b94c9e9a643dccaefcbfde4e38fcee6a03468deabf391d0d5eeef6d239d51477cd8f38a48c26b19fd1a8b11cc7632970364328dce",
          "sha256": "61f468f2496c7963755c8f1d903b485669f2c9feca1344ffa3641bdab9aee435",
          "sha1": "1d9ed63f2558ea31bed3e81e6b10008d03865a60",
          "md5": "c3e079f99c502a13c4e1d1106bff6405"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "buildtools-1.0.3-all.jar",
          "url": "buildtools-1.0.3-all.jar",
          "size": 78585788,
          "sha512": "0e166834dd333321869e1aaa41bdb33e4548da24bdb108f50bc0b086ff3fa222c0048a93da010064ea3324c8f534c346cb66b48eaa9a1ebd116b3ac126371b4d",
          "sha256": "f8c928b2614df4a46573465230d890177fb7f65143d1ecaabdc9131388a70976",
          "sha1": "1a81ad5444ea22d564a52716cabe50e2ab383471",
          "md5": "c64c19b3cf5d8817bbadd268febb4e0e"
        }
      ]
    }
  ]
}
