{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pixlfox.scriptablemc",
    "module": "buildtools",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "buildtools-1.0.0-SNAPSHOT.jar",
          "url": "buildtools-1.0.0-SNAPSHOT.jar",
          "size": 57932,
          "sha512": "6871875d642aaba77210af7be387b284e61a34dbd4157967a57ea0a903b5d90d4a0ac6f16d1570711f27e02950508325284195b7b95017401059fd42c492bf70",
          "sha256": "c85d9b107cc8d87617274beaf80e498f19769f08eb8438b8740aa18bdeb8a5fa",
          "sha1": "725daa0bd3b3a46bbd2b3cda31dbd53d77474b13",
          "md5": "f146c7aeebf07b925f30152eeab77671"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.15"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        }
      ],
      "files": [
        {
          "name": "buildtools-1.0.0-SNAPSHOT.jar",
          "url": "buildtools-1.0.0-SNAPSHOT.jar",
          "size": 57932,
          "sha512": "6871875d642aaba77210af7be387b284e61a34dbd4157967a57ea0a903b5d90d4a0ac6f16d1570711f27e02950508325284195b7b95017401059fd42c492bf70",
          "sha256": "c85d9b107cc8d87617274beaf80e498f19769f08eb8438b8740aa18bdeb8a5fa",
          "sha1": "725daa0bd3b3a46bbd2b3cda31dbd53d77474b13",
          "md5": "f146c7aeebf07b925f30152eeab77671"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "buildtools-1.0.0-SNAPSHOT-all.jar",
          "url": "buildtools-1.0.0-SNAPSHOT-all.jar",
          "size": 78585788,
          "sha512": "b42a4d571e9fa8b274d4bf45b0bfb52d6b7e8bddf19e4e30bb9517c9c0fd3e27978b4e5ff2e43c8ff998edcfa9e481697ae5c2928b8ff5f7ac7368607e0471f9",
          "sha256": "bf0284808a3e8e7e6fb000e5c69f00f507403ba78507c6728a783d88cff2ccb8",
          "sha1": "d3b47fa8d26304d20cb1b16bba8baf1dcb8b5344",
          "md5": "7d09879f274b29eab05140521d6018f5"
        }
      ]
    }
  ]
}
