{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pixlfox.scriptablemc",
    "module": "buildtools",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "buildtools-1.0.0-SNAPSHOT.jar",
          "url": "buildtools-1.0.0-SNAPSHOT.jar",
          "size": 58015,
          "sha512": "f80eaddf6e68f1a0efef53bba005648e25fddcd53921d31bbf95c7d159544c55dcdb93da3c557dd795b7e31d341a5e0ed8ba23deb935d6bf0ddcd811a5504230",
          "sha256": "4bb17a7deecc01b058e617533277cfab5bc31eb257c106c3b974357cbaf5b855",
          "sha1": "7980bed162a519739fa1f752dfe89cf7601c41c4",
          "md5": "b93c9ed42df496d9898a9d0e1c63c006"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.15"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        }
      ],
      "files": [
        {
          "name": "buildtools-1.0.0-SNAPSHOT.jar",
          "url": "buildtools-1.0.0-SNAPSHOT.jar",
          "size": 58015,
          "sha512": "f80eaddf6e68f1a0efef53bba005648e25fddcd53921d31bbf95c7d159544c55dcdb93da3c557dd795b7e31d341a5e0ed8ba23deb935d6bf0ddcd811a5504230",
          "sha256": "4bb17a7deecc01b058e617533277cfab5bc31eb257c106c3b974357cbaf5b855",
          "sha1": "7980bed162a519739fa1f752dfe89cf7601c41c4",
          "md5": "b93c9ed42df496d9898a9d0e1c63c006"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "buildtools-1.0.0-SNAPSHOT-all.jar",
          "url": "buildtools-1.0.0-SNAPSHOT-all.jar",
          "size": 78585871,
          "sha512": "f6673a10f4bd7f68161b9e390845bc90ded9d27280881de3b4f1c1344496ee4fb4b0ab3e8499e2d1c846028536dd968cf45328acf33af5037f0cefa866057791",
          "sha256": "b8144a728892bdaa9c9d67d1983aa31728a50b84892ae76aa3fe49c60e5d072f",
          "sha1": "3bfcfd98ce86e4a66b85685c3b05b6d7171b7e46",
          "md5": "8cf8627e9ba97c7994489940e12b7d14"
        }
      ]
    }
  ]
}
