name: Build Dev
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Fix gradlew permissions
      run: chmod +x ./gradlew
    - name: Build plugin jar files with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew publish