name: Build Dev
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Fix gradlew permissions
      run: chmod +x ./gradlew
    - name: Build gradle plugin
      run: ./gradlew :buildtools:publishAllPublicationsToLocalMavenFSRepository
    - uses: actions/upload-artifact@v1
        with:
          name: maven-repo
          path: maven-repo/